### ISSUE TITLE
What is the license of the project?

### ISSUE THREAD

**Issue by visortelle** [mariatsji/type-depict#1]
Hello! I wanted to ask, do you mind if I'll integrate it with this extension and noticed that there is no license in the repo. 🙂

Thank you.
 
https://marketplace.visualstudio.com/items?itemName=visortelle.haskell-spotlight

https://github.com/haskell-spotlight/haskell-spotlight

**Comment by mariatsji** [comment]
Hi!
I chose the MIT license, go ahead with the integration, it sounds fun :)

**Comment by mariatsji** [comment]
Would it be preferable with an /api or similar http endpoint, or would Haskell Spotlight use the code as a lib perhaps?

**Comment by visortelle** [comment]
At first look, the simplest would be API that responds with an SVG string.

It would be probably nice to have classes instead of hardcoded colors to have the ability to style them.

I can probably start with parsing the current HTML response, then see the result and we can make some changes if needed.

Haskell Spotlight doesn't use any Haskell code and doesn't have a server-side except for the simplest possible proxy to Hoogle and Hackage + server-side rendering with NextJS for React components. If you are asking because you don't want to maintain the type-depict deployment, I can maintain my own instance.

**Comment by mariatsji** [comment]
HTML parse sounds like a good start.
I have plans to host this app under the type-depict.io domain for 2 years, but in practice I believe I will continue to host it for longer.
Classes for the colors in the SVG was a good idea, I`ll check to see if it is easy to add wit the svg-builder lib I am using

**Comment by visortelle** [comment]
Great. Then let's close this issue. I'll let you know when will be something to show.

**Comment by mariatsji** [comment]
Cool, I put up an /api endpoint to make it a little easier for you, serving only the <svg> as **image/svg+xml**
